export const rmgAndTextileDepartments = [
    "Production",
    "Quality Control",
    "Merchandising",
    "Marketing & Merchandising",
    "Planning",
    "Design and Development",
    "R & D",
    "Fabric Sourcing",
    "Cutting",
    "Sewing",
    "Finishing",
    "Industrial Engineering (IE)",
    "Dyeing",
    "Knitting",
    "Printing",
    "Maintenance",
    "Human Resources",
    "Compliance",
    "Procurement",
    "Inventory Management",
    "Chemical Store",
    "Accessories Store",
    "General Store",
    "Logistics",
    "Export Documentation",
    "Accounts and Finance",
    "IT",
    "Health and Safety",
    "Training and Development"
];


export const rmgAndTextileDesignations = [
    "Junior Officer",
    "Officer",
    "Supervisor",
    "Assistant Supervisor",
    "Junior Executive",
    "Executive",
    "Senior Executive",
    "Assistant Manager",
    "Deputy Manager",
    "Manager",
    "Assistant General Manager",
    "General Manager",
    "Senior General Manager",
    "Chief Operating Officer",
    "Chief Financial Officer",
    "Chief Executive Officer",
    "Director",
    "Chairman",
    "Managing Director"
];

